defmodule CalcRel.Repo.Migrations.AddUrlInfos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sites) do
      add(:domain, :text)
    end

    alter table(:scans) do
      add(:query_str, :text)
    end

    alter table(:pages) do
      add(:path, :text)
    end
  end

  def down do
    alter table(:pages) do
      remove(:path)
    end

    alter table(:scans) do
      remove(:query_str)
    end

    alter table(:sites) do
      remove(:domain)
    end
  end
end
